<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <NoWarn>$(NoWarn);NU1605;NU1608</NoWarn>
        <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="AttributionTests.fs" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../src/FxLib/FxLib.fsproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="xunit.v3.mtp-v2" />
    </ItemGroup>

</Project>
